version: '3'
services:

  xilinx-base:
    container_name: xilinx-base
    privileged: true
    restart: always
    build:
       context: .
       dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: host

